# Generated by Django 4.2.23 on 2025-08-17 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_created_at_remove_review_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='predicted_rating',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
